### ISSUE TITLE
Unable to install on Win10

### ISSUE THREAD

**Issue by OliPassey** [mrjumpingjack/LaunchPadForOBS#2]
Hey,
Just found this app and tried to install, it tries to download .net 4.7.2 - can't for some reason and then quits.
I have the latest .net installed, so the installer would fail even if it had downloaded and ran.

Any idea if something has changed in latest version of something, or do i need a specific .net build? 
I note it's downloading a german edition, im in the UK - and don't really want to start mixing languages if at all possible.

Any feedback would be much appreciated.
Cheers,
Oli

**Comment by OliPassey** [comment]
`PLATFORM VERSION INFO
	Windows 			: 10.0.18363.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.8.4200.0 built by: NET48REL1LAST_C
	clr.dll 			: 4.8.4200.0 built by: NET48REL1LAST_C
	dfdll.dll 			: 4.8.4200.0 built by: NET48REL1LAST_C
	dfshim.dll 			: 10.0.18362.1 (WinBuild.160101.0800)

SOURCES
	Deployment url			: file:///C:/Users/Oli/Desktop/LaunchPad%20for%20OBS.application

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\Oli\Desktop\LaunchPad for OBS.application resulted in exception. Following failure messages were detected:
		+ Downloading file:///C:/Users/Oli/Desktop/LaunchPad for OBS.application did not succeed.
		+ Could not find file 'C:\Users\Oli\Desktop\LaunchPad for OBS.application'.
		+ Could not find file 'C:\Users\Oli\Desktop\LaunchPad for OBS.application'.
		+ Could not find file 'C:\Users\Oli\Desktop\LaunchPad for OBS.application'.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [06/08/2020 23:45:20] : Activation of C:\Users\Oli\Desktop\LaunchPad for OBS.application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [06/08/2020 23:45:20] System.Deployment.Application.DeploymentDownloadException (Unknown subtype)
		- Downloading file:///C:/Users/Oli/Desktop/LaunchPad for OBS.application did not succeed.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState, X509Certificate2 clientCertificate)
			at System.Deployment.Application.DownloadManager.DownloadManifestAsRawFile(Uri& sourceUri, String targetPath, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestDirectBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Net.WebException
		- Could not find file 'C:\Users\Oli\Desktop\LaunchPad for OBS.application'.
		- Source: System
		- Stack trace:
			at System.Net.FileWebRequest.EndGetResponse(IAsyncResult asyncResult)
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
		--- Inner Exception ---
		System.Net.WebException
		- Could not find file 'C:\Users\Oli\Desktop\LaunchPad for OBS.application'.
		- Source: System
		- Stack trace:
			at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
			at System.Net.FileWebRequest.GetResponseCallback(Object state)
		--- Inner Exception ---
		System.IO.FileNotFoundException
		- Could not find file 'C:\Users\Oli\Desktop\LaunchPad for OBS.application'.
		- Source: mscorlib
		- Stack trace:
			at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
			at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
			at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
			at System.Net.FileWebStream..ctor(FileWebRequest request, String path, FileMode mode, FileAccess access, FileShare sharing, Int32 length, Boolean async)
			at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

`

**Comment by mrjumpingjack** [comment]
Fixed missing files in precompiled download. If you download precompiled app again it should work. 
Thanks for your feedback :)
